// Generated by CoffeeScript 1.4.0
var Bender, Command, FenderBender, log, srv,
  __slice = [].slice,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Command = require('commander');

srv = require('http');

log = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

srv.get('http://registry.npmjs.org/' + 'docpad', function(callback) {
  return log(callback);
});

Bender = (function(_super) {

  __extends(Bender, _super);

  function Bender(instanceId) {
    this.instanceId = instanceId != null ? instanceId : new Date().getTime();
  }

  return Bender;

})(Command);

FenderBender = (function(_super) {

  __extends(FenderBender, _super);

  function FenderBender() {
    return FenderBender.__super__.constructor.apply(this, arguments);
  }

  return FenderBender;

})(Bender);
