// Generated by CoffeeScript 1.4.0

({
  name: "",
  version: "0.0.1",
  "private": true,
  dependencies: {
    doctoc: "*",
    docco: "*",
    crojsdoc: "*",
    dox: "*",
    markdox: "*"
  },
  scripts: {
    freeze: "npm shrikwrap"
  }
});
